Algoritmo "EscolhaCaso2"


Var
// Seção de Declarações das variáveis 
mes:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc..
escreval ("Entre com um mês: ")
leia(mes)

escolha mes
        caso 1
        escreval ("Janeiro")
        caso 2
        escreval ("Fevereiro")
        caso 3
        escreval ("Março")
        outrocaso
        escreval ("Não é Janeiro,nem Fevereiro e nem Março! É outro mês! ")
fimescolha

Fimalgoritmo
