Algoritmo "EnquantoFaca"
//
Var
// Seção de Declarações das variáveis 
contador:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
contador <- 1//para o contador receber 1
enquanto contador <= 10 faca
escreval(contador)
contador <- contador + 1
fimenquanto

escreval("REPETIÇÃO")
contador <- 1
repita
escreval(contador)
contador <- contador + 1
ate contador > 10

Fimalgoritmo